name: Terraform Cleanup

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform init -input=false

      - name: Terraform Destroy
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform destroy -target=azurerm_container_group.chuie_aci -auto-approve -input=false -var="image_tag=${{ github.sha }}" -var="django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}"
