name: Docker Build Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run custom action
        uses: ./.github/actions/docker-smoke-test
        with:
          image-name: my-app
          port: "8000"
          secret-key: ${{ secrets.DJANGO_SECRET_KEY }}
