name: Docker Build Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run custom action
        uses: ./.github/actions/docker-smoke-test
        with:
          image-name: my-app
          port: "8000"
          secret-key: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        with:
          image: my-app:latest
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Scan SBOM
        uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e
        with:
          sbom: sbom.spdx.json
          fail-build: fail
          severity-cutoff: critical
          output-format: table
          output-file: grype-report.txt

      - name: Upload scan report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: grype-report
          path: grype-report.txt

      - name: Upload SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sbom
          path: sbom.spdx.json
