name: Docker Build Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run custom action
        uses: ./.github/actions/docker-smoke-test
        with:
          image-name: my-app
          port: "8000"
          secret-key: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: my-app:latest
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Scan SBOM
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.spdx.json
          fail-build: false
          severity-cutoff: high

      - name: Uplaod SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
