name: Terraform Force Unlock

on:
  workflow_dispatch:

jobs:
  unlock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init
        working-directory: .

      - name: Force unlock state
        run: terraform force-unlock -force a7946c5b-787d-8318-3bfd-5fe8326d0fe5
        working-directory: .
