name: build-test-scan-deploy

on:
  workflow_dispatch:

jobs:
  build-test-scan-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run custom action
        uses: ./.github/actions/docker-smoke-test
        with:
          image-name: my-app
          port: "8000"
          secret-key: ${{ secrets.DJANGO_SECRET_KEY }}

      - name: Generate SBOM
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610
        with:
          image: my-app:latest
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Scan SBOM
        uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e
        with:
          sbom: sbom.spdx.json
          fail-build: false
          severity-cutoff: critical
          output-format: table
          output-file: grype-report.txt

      - name: Upload scan report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: grype-report
          path: grype-report.txt

      - name: Upload SBOM
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Azure Login
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        if: github.ref == 'refs/heads/main'
        run: az acr login --name acrchuieacmp2400

      - name: Tag image for ACR
        if: github.ref == 'refs/heads/main'
        run: docker tag my-app acrchuieacmp2400.azurecr.io/my-app:${{ github.sha }}

      - name: Push image to ACR
        if: github.ref == 'refs/heads/main'
        run: docker push acrchuieacmp2400.azurecr.io/my-app:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: |
          terraform plan -no-color \
          -input=false \
          -lock-timeout=60s \
          -var="django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}" \
          -var="image_tag=${{ github.sha }}" \

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          STATE_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve -input=false \
                -var="image_tag=${{ github.sha }}" \
                -var="django_secret_key=${{ secrets.DJANGO_SECRET_KEY }}" \
